version: '3'
services:
  sonarqube-postgres:
    container_name: sonarqube-postgres
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    ports:
      - 5432:5432
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarnet

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    restart: always
    ports:
      - "9000:9000"
    environment:
      - sonar.jdbc.url==jdbc:postgresql://sonarqube-postgres/sonarqube
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - SONAR_WEB_CONTEXT=/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - sonarnet
    depends_on:
      - sonarqube-postgres

networks:
  sonarnet:
  
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
